### ISSUE TITLE
Two config files

### ISSUE THREAD

**Issue by courtneytkacz** [courtneytkacz/vmfa-digcoll-map#2]
@chrisdaaz 

Why does this repo have two config YAML files? One is titled "_config_production.yml" and the other just "_config.yml", so I would guess that one is just to test config settings, but they both had identical contents. (Please note that I have since updated the configs with my own information, and I updated it in both places so they are still identical.)

**Comment by chrisdaaz** [comment]
@courtneytkacz 

i haven't seen this exact set up before, so i'm not sure, but it's likely that they deployed this website to a production server (hosted elsewhere) *in addition* to github pages. it **is** common to have separate configuration files for each server deployment environment (e.g. development, staging, production), so i'm guessing they had / have something like that. the `_config.yml` is all you would need. it's what's governing the settings for https://courtneytkacz.github.io/vmfa-digcoll-map/

**Comment by courtneytkacz** [comment]
That makes sense. I removed the production config file the correct way this time (using git rm) and it worked great.
